[redis] # Used by SessionManager
address = "127.0.0.1"
port = 6379

[sql] # Used by DatabaseManager
uri_string = "sqlite:///database.db"

[logger]
file_path = "elma.log"

[server] # Used by FastAPI
address = "0.0.0.0"
port = 8000