[project]
name = "ai-mail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "fastmcp>=4.0.5",
    "fastmcp-slim[server]>=4.0.5",
    "pydantic>=2.13.5",
    "pyjwt>=2.14.0",
    "pyright>=1.1.414",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "sqlmodel>=0.0.42",
    "uuid>=1.30",
]
